
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def viewListPage(window):
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 322,
        width = 584,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        322.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        311.0,
        fill="#6D6B6B",
        outline="")

    canvas.create_rectangle(
        15.0,
        44.0,
        573.0,
        267.0,
        fill="#424141",
        outline="")

    canvas.create_rectangle(
        20.0,
        49.0,
        564.0,
        125.0,
        fill="#262626",
        outline="")

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        471.5,
        290.5,
        image=entry_image_1
    )
    entry_1 = Text(
        bd=0,
        bg="#D9D9D9",
        highlightthickness=0
    )
    entry_1.place(
        x=392.0,
        y=280.0,
        width=159.0,
        height=19.0
    )

    canvas.create_text(
        342.0,
        282.0,
        anchor="nw",
        text="Name:",
        fill="#000000",
        font=("Inter", 12 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=168.0,
        y=280.0,
        width=50.0,
        height=20.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=98.0,
        y=280.0,
        width=50.0,
        height=20.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=29.0,
        y=280.0,
        width=50.0,
        height=20.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        472.5,
        87.0,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#D9D9D9",
        highlightthickness=0
    )
    entry_2.place(
        x=394.0,
        y=74.0,
        width=157.0,
        height=24.0
    )

    canvas.create_rectangle(
        29.0,
        59.0,
        372.0,
        114.0,
        fill="#D9D9D9",
        outline="")

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        59.5,
        87.0,
        image=entry_image_3
    )
    entry_3 = Text(
        bd=0,
        bg="#8F0000",
        highlightthickness=0
    )
    entry_3.place(
        x=37.0,
        y=68.0,
        width=45.0,
        height=36.0
    )

    canvas.create_rectangle(
        0.0,
        0.0,
        584.0,
        34.0,
        fill="#5D5FEF",
        outline="")

    canvas.create_text(
        136.0,
        2.0,
        anchor="nw",
        text="View List",
        fill="#000000",
        font=("Inter", 24 * -1)
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=509.0,
        y=7.0,
        width=59.0,
        height=21.0
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_5 clicked"),
        relief="flat"
    )
    button_5.place(
        x=15.0,
        y=6.0,
        width=59.0,
        height=20.0
    )
    window.resizable(False, False)
    window.mainloop()
